#!/bin/sh
set -u
set -e

# install scl repos, epel, and python 36
yum install -y centos-release-scl epel-release \
    && yum-config-manager --enable rhel-server-rhscl-7-rpms \
    && yum install -y rh-python36
